services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222" # NATS client connections
      - "6222:6222" # Cluster routes
      - "8222:8222" # HTTP monitoring
    command: [
        "-js", # Enable JetStream
        "-sd",
        "/data", # Store directory
        "-m",
        "8222", # HTTP monitoring port
      ]
    volumes:
      - nats_data:/data
    networks:
      - centrifugo-network
    restart: unless-stopped

  nats-stream-init:
    image: natsio/nats-box:latest
    container_name: nats-stream-init
    depends_on:
      - nats
    networks:
      - centrifugo-network
    command:
      - sh
      - -c
      - |
        echo 'Waiting for NATS to be ready...'
        while ! nats server check connection --server=nats://nats:4222 2>/dev/null; do
          echo 'NATS not ready, waiting...'
          sleep 2
        done
        echo 'NATS is ready! Creating EVENTS stream...'
        nats stream add EVENTS --subjects 'events.>' --storage file --retention limits --max-msgs=-1 --max-bytes=-1 --max-age='' --max-msg-size=-1 --dupe-window=2m --replicas=1 --server=nats://nats:4222 --defaults
        echo 'EVENTS stream created successfully!'
    restart: "no"

  centrifugo:
    image: centrifugo/centrifugo:v6.2.1
    container_name: centrifugo-server
    ports:
      - "8000:8000" # Centrifugo HTTP/SSE
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json:ro
    command: centrifugo -c config.json
    depends_on:
      nats-stream-init:
        condition: service_completed_successfully
    networks:
      - centrifugo-network
    restart: unless-stopped
    environment:
      - CENTRIFUGO_LOG_LEVEL=debug

volumes:
  nats_data:
    driver: local

networks:
  centrifugo-network:
    driver: bridge
