[jwt]
secret = "very-very-secret-key"
ttl = { secs = 86400, nanos = 0 }

[api]
address = "0.0.0.0:8080"

[storage]
database_url = "mongodb://mongodb:27017/zkmsngr?replicaSet=rs0"
database_name = "zkmsngr"
