[centrifugo]
hmac_secret = "tkE0hTS953BL3ETHeFyHGY3cAl78xyGCdPCtsGIX-oiyJ_Suz_ui_j3Gjrp8JP62Lq8tHCoih6rBMeUvfGPOvw"
ttl = { secs = 86400, nanos = 0 }

[api]
address = "0.0.0.0:8080"

[storage]
database_url = "mongodb://mongodb:27017/zkmsngr?replicaSet=rs0"
database_name = "zkmsngr"
