[centrifugo]
hmac_secret = "tkE0hTS953BL3ETHeFyHGY3cAl78xyGCdPCtsGIX-oiyJ_Suz_ui_j3Gjrp8JP62Lq8tHCoih6rBMeUvfGPOvw"
ttl = { secs = 86400, nanos = 0 }

[api]
address = "0.0.0.0:8080"
merge_changes = false

[storage]
database_url = "mongodb://mongodb:27017/zkartgroup?replicaSet=rs0"
database_name = "zkartgroup"

[nats]
messages_namespace = "personal"
