[logging]
level = "debug"

[storage]
database_url = "mongodb://mongodb:27017/zkartgroup?replicaSet=rs0"
database_name = "zkartgroup"
messages_outbox_collection_name = "messages_outbox"

[nats]
url = "nats://nats:4222"
subject = "events.>"
messages_namespace = "personal"
