[logging]
level = "debug"

[storage]
database_url = "mongodb://mongodb:27017/zkmsngr?replicaSet=rs0"
database_name = "zkmsngr"
messages_outbox_collection_name = "messages_outbox"
group_operations_outbox_collection_name = "group_operations_outbox"

[nats]
url = "nats://nats:4222"

# [nats]
# url = "nats://nats:4222"
# stream_name = "zkmsngr"
# consumer_name = "zkmsngr-relay"
